export const HPA_TO_MMHG=0.750061683;
export const SESSIONS={evening:{date:'2026-09-19',name:'Вечер',min:16,max:22,hour:18,window:'18:00–20:30',sun:'Закат 19:05'},morning:{date:'2026-09-20',name:'Утро',min:4,max:10,hour:6,window:'05:40–08:30',sun:'Восход 06:39'}};
export const finite=v=>typeof v==='number'&&Number.isFinite(v);
export const format=(v,d=1)=>finite(v)?v.toLocaleString('ru-RU',{maximumFractionDigits:d,minimumFractionDigits:d,useGrouping:false}):'—';
export const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function windDirection(deg){return finite(deg)?['С','ССВ','СВ','ВСВ','В','ВЮВ','ЮВ','ЮЮВ','Ю','ЮЮЗ','ЮЗ','ЗЮЗ','З','ЗСЗ','СЗ','ССЗ'][Math.round(deg/22.5)%16]:'—'}
export function hourRow(data,date,hour){const time=`${date}T${String(hour).padStart(2,'0')}:00`;const i=data.hourly.time.indexOf(time);if(i<0)return null;return Object.fromEntries(Object.entries(data.hourly).map(([k,v])=>[k,v[i]??null]));}
export function trend(data,time,hours){const i=data.hourly.time.indexOf(time);if(i<hours)return null;const a=data.hourly.pressure_msl[i],b=data.hourly.pressure_msl[i-hours];return finite(a)&&finite(b)?a-b:null;}
export function validateWeather(data){if(data?.timezone!=='Asia/Yekaterinburg'||data?.utc_offset_seconds!==18000)throw Error('Неожиданный часовой пояс прогноза');const h=data.hourly;if(!h||!Array.isArray(h.time))throw Error('Нет почасовых данных');for(const key of ['temperature_2m','surface_pressure','pressure_msl','wind_speed_10m','wind_gusts_10m','wind_direction_10m','precipitation','cloud_cover','visibility','weather_code'])if(!Array.isArray(h[key])||h[key].length!==h.time.length)throw Error(`Неполные данные: ${key}`);for(const s of Object.values(SESSIONS))for(let t=s.min;t<=s.max;t++){const row=hourRow(data,s.date,t);if(!row||!finite(row.pressure_msl)||!finite(row.wind_speed_10m))throw Error('Прогноз не покрывает оба выхода');}return data;}
export function haversine(a,b){const r=x=>x*Math.PI/180;const dlat=r(b[0]-a[0]),dlon=r(b[1]-a[1]);const h=Math.sin(dlat/2)**2+Math.cos(r(a[0]))*Math.cos(r(b[0]))*Math.sin(dlon/2)**2;return 6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}
export function validCoord(lon,lat){return finite(lon)&&finite(lat)&&lon>=60.23&&lon<=60.61&&lat>=55.27&&lat<=55.58;}
export function parseDepthFile(text,filename){if(text.length>5000000)throw Error('Максимум 5 МБ');let fc;if(filename.toLowerCase().endsWith('.csv')){const lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/);const delimiter=lines[0].includes(';')?';':',';const keys=lines.shift().toLowerCase().split(delimiter).map(x=>x.trim());const cols=['lat','lon','depth'].map(k=>keys.indexOf(k));if(cols.includes(-1))throw Error('Нужны столбцы lat,lon,depth. Координаты WGS84, глубина в метрах.');fc={type:'FeatureCollection',features:lines.filter(x=>x.trim()).map(line=>{const vals=line.split(delimiter).map(x=>x.trim());const num=k=>vals[k]===undefined||vals[k]===''?NaN:Number(vals[k]);return {type:'Feature',properties:{depth:num(cols[2])},geometry:{type:'Point',coordinates:[num(cols[1]),num(cols[0])]}}})};}else{try{fc=JSON.parse(text)}catch{throw Error('Файл не является корректным GeoJSON')}}
if(fc.type==='Feature')fc={type:'FeatureCollection',features:[fc]};if(fc.type!=='FeatureCollection'||!Array.isArray(fc.features)||fc.features.length===0)throw Error('В файле нет промеров или изобат');if(fc.features.length>10000)throw Error('Не более 10 000 объектов');let vertices=0;const clean=fc.features.map(f=>{const d=f.properties?.depth;if(!finite(d)||d<0||d>50)throw Error('Каждому объекту нужна depth от 0 до 50 м');const g=f.geometry;if(!g||!['Point','LineString','MultiLineString'].includes(g.type))throw Error('Допустимы Point, LineString и MultiLineString');const lines=g.type==='Point'?[[g.coordinates]]:g.type==='LineString'?[g.coordinates]:g.coordinates;if(!Array.isArray(lines)||!lines.length)throw Error('Пустая геометрия');for(const line of lines){if(!Array.isArray(line)||line.length<(g.type==='Point'?1:2))throw Error('Неполная геометрия');for(const c of line){if(!Array.isArray(c)||!validCoord(c[0],c[1]))throw Error('Координаты должны быть в районе Аргази: [долгота, широта]');if(++vertices>100000)throw Error('Слишком много координат')}}return {type:'Feature',properties:{depth:d},geometry:g}});return {type:'FeatureCollection',features:clean};}
export function toGPX(spots){return `<?xml version="1.0" encoding="UTF-8"?><gpx version="1.1" creator="Argazi planner" xmlns="http://www.topografix.com/GPX/1/1"><metadata><name>Аргази — районы поиска, не навигационный маршрут</name><desc>19–20 сентября 2026. Глубины и безопасность прохода проверять на воде.</desc></metadata>${spots.map(s=>`<wpt lat="${s.lat}" lon="${s.lon}"><name>${escapeHTML(s.name)}</name><desc>${escapeHTML(s.description||'Авторский центр района поиска. Промер эхолотом обязателен.')}</desc></wpt>`).join('')}</gpx>`;}
